// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// ⚠️ PENDIENTE DE REGENERAR. Estos ids vienen heredados de la app de CLIENTES
/// (`sozu-cliente-app`): el proyecto de Firebase es el correcto
/// (`sozu-admin-prd`) pero los `appId` de Android e iOS son de las apps del
/// cliente. Mientras no se registren las apps del bundle
/// `com.sozu.agentes_app` / `com.sozu.sozuAgenteApp` y no se regenere este
/// archivo con `flutterfire configure`, los push del agente llegarían a la app
/// equivocada y el build de Android falla en el plugin de Google Services
/// ("No matching client found for package name"). La web NO usa este archivo,
/// así que el localhost y el deploy de hosting funcionan igual.
///
/// Example:
/// ```dart
/// import 'package:sozu_agente_app/firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBi_e43N8DiR34RwAYaAJKeTlNzGoVCAzk',
    appId: '1:334194000163:android:3faec92654ee45a09a8c96',
    messagingSenderId: '334194000163',
    projectId: 'sozu-admin-prd',
    storageBucket: 'sozu-admin-prd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFThDpr_h4gEsWCWlLVZukZJZWDyVFNJs',
    appId: '1:334194000163:ios:c1972723d94e278e9a8c96',
    messagingSenderId: '334194000163',
    projectId: 'sozu-admin-prd',
    storageBucket: 'sozu-admin-prd.firebasestorage.app',
    iosBundleId: 'com.sozu.sozuAgenteApp',
  );
}
