// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Generado con los ids de las apps de AGENTES del proyecto sozu-admin-prd
/// (`SOZU Agentes Android` con package com.sozu.agentes_app y `SOZU Agentes iOS`
/// con bundle com.sozu.sozuAgenteApp). Si se registra otra app o se cambia el
/// bundle, hay que volver a bajar los archivos: `google-services.json`,
/// `GoogleService-Info.plist` y estos ids tienen que apuntar todos a lo mismo o
/// los push del agente llegan a la app equivocada.
///
/// Example:
/// ```dart
/// import 'package:sozu_agente_app/firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBi_e43N8DiR34RwAYaAJKeTlNzGoVCAzk',
    appId: '1:334194000163:android:6800f8d827ea4c9c9a8c96',
    messagingSenderId: '334194000163',
    projectId: 'sozu-admin-prd',
    storageBucket: 'sozu-admin-prd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFThDpr_h4gEsWCWlLVZukZJZWDyVFNJs',
    appId: '1:334194000163:ios:02fe9a130f72d2209a8c96',
    messagingSenderId: '334194000163',
    projectId: 'sozu-admin-prd',
    storageBucket: 'sozu-admin-prd.firebasestorage.app',
    iosBundleId: 'com.sozu.sozuAgenteApp',
  );
}
